/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART 1 transmit data source select: UART1_TX pin */

/*! @name PORTC4 (coord A9), J1[4]/UART1_TX/FTM0_CH3/FB_AD11
  @{ */
#define BOARD_UART1_TX_PERIPHERAL UART1                        /*!<@brief Device name: UART1 */
#define BOARD_UART1_TX_SIGNAL TX                               /*!<@brief UART1 signal: TX */
#define BOARD_UART1_TX_PORT PORTC                              /*!<@brief PORT device name: PORTC */
#define BOARD_UART1_TX_PIN 4U                                  /*!<@brief PORTC pin index: 4 */
#define BOARD_UART1_TX_PIN_NAME UART1_TX                       /*!<@brief Pin name */
#define BOARD_UART1_TX_LABEL "J1[4]/UART1_TX/FTM0_CH3/FB_AD11" /*!<@brief Label */
#define BOARD_UART1_TX_NAME "UART1_TX"                         /*!<@brief Identifier name */
#define BOARD_UART1_TX_DIRECTION kPIN_MUX_DirectionOutput      /*!<@brief Direction */
                                                               /* @} */

/*! @name PORTC3 (coord A11), J1[2]/UART1_RX/FTM0_CH2/CLKOUT
  @{ */
#define BOARD_UART1_RX_PERIPHERAL UART1                       /*!<@brief Device name: UART1 */
#define BOARD_UART1_RX_SIGNAL RX                              /*!<@brief UART1 signal: RX */
#define BOARD_UART1_RX_PORT PORTC                             /*!<@brief PORT device name: PORTC */
#define BOARD_UART1_RX_PIN 3U                                 /*!<@brief PORTC pin index: 3 */
#define BOARD_UART1_RX_PIN_NAME UART1_RX                      /*!<@brief Pin name */
#define BOARD_UART1_RX_LABEL "J1[2]/UART1_RX/FTM0_CH2/CLKOUT" /*!<@brief Label */
#define BOARD_UART1_RX_NAME "UART1_RX"                        /*!<@brief Identifier name */
                                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name PORTD11 (coord B2), SW2
  @{ */
#define BOARD_SW2_PERIPHERAL GPIOD                  /*!<@brief Device name: GPIOD */
#define BOARD_SW2_SIGNAL GPIO                       /*!<@brief GPIOD signal: GPIO */
#define BOARD_SW2_GPIO GPIOD                        /*!<@brief GPIO device name: GPIOD */
#define BOARD_SW2_GPIO_PIN 11U                      /*!<@brief PORTD pin index: 11 */
#define BOARD_SW2_PORT PORTD                        /*!<@brief PORT device name: PORTD */
#define BOARD_SW2_PIN 11U                           /*!<@brief PORTD pin index: 11 */
#define BOARD_SW2_CHANNEL 11                        /*!<@brief GPIOD GPIO channel: 11 */
#define BOARD_SW2_PIN_NAME PTD11                    /*!<@brief Pin name */
#define BOARD_SW2_LABEL "SW2"                       /*!<@brief Label */
#define BOARD_SW2_NAME "SW2"                        /*!<@brief Identifier name */
#define BOARD_SW2_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                    /* @} */

/*! @name PORTA10 (coord M9), SW3
  @{ */
#define BOARD_SW3_PERIPHERAL GPIOA                  /*!<@brief Device name: GPIOA */
#define BOARD_SW3_SIGNAL GPIO                       /*!<@brief GPIOA signal: GPIO */
#define BOARD_SW3_GPIO GPIOA                        /*!<@brief GPIO device name: GPIOA */
#define BOARD_SW3_GPIO_PIN 10U                      /*!<@brief PORTA pin index: 10 */
#define BOARD_SW3_PORT PORTA                        /*!<@brief PORT device name: PORTA */
#define BOARD_SW3_PIN 10U                           /*!<@brief PORTA pin index: 10 */
#define BOARD_SW3_CHANNEL 10                        /*!<@brief GPIOA GPIO channel: 10 */
#define BOARD_SW3_PIN_NAME PTA10                    /*!<@brief Pin name */
#define BOARD_SW3_LABEL "SW3"                       /*!<@brief Label */
#define BOARD_SW3_NAME "SW3"                        /*!<@brief Identifier name */
#define BOARD_SW3_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONs(void);

/*! @name PORTA11 (coord L9), LEDRGB_BLUE
  @{ */
#define BOARD_LED_BLUE_PERIPHERAL GPIOA                   /*!<@brief Device name: GPIOA */
#define BOARD_LED_BLUE_SIGNAL GPIO                        /*!<@brief GPIOA signal: GPIO */
#define BOARD_LED_BLUE_GPIO GPIOA                         /*!<@brief GPIO device name: GPIOA */
#define BOARD_LED_BLUE_GPIO_PIN 11U                       /*!<@brief PORTA pin index: 11 */
#define BOARD_LED_BLUE_PORT PORTA                         /*!<@brief PORT device name: PORTA */
#define BOARD_LED_BLUE_PIN 11U                            /*!<@brief PORTA pin index: 11 */
#define BOARD_LED_BLUE_CHANNEL 11                         /*!<@brief GPIOA GPIO channel: 11 */
#define BOARD_LED_BLUE_PIN_NAME PTA11                     /*!<@brief Pin name */
#define BOARD_LED_BLUE_LABEL "LEDRGB_BLUE"                /*!<@brief Label */
#define BOARD_LED_BLUE_NAME "LED_BLUE"                    /*!<@brief Identifier name */
#define BOARD_LED_BLUE_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                          /* @} */

/*! @name PORTE6 (coord E1), LEDRGB_GREEN
  @{ */
#define BOARD_LED_GREEN_PERIPHERAL GPIOE                   /*!<@brief Device name: GPIOE */
#define BOARD_LED_GREEN_SIGNAL GPIO                        /*!<@brief GPIOE signal: GPIO */
#define BOARD_LED_GREEN_GPIO GPIOE                         /*!<@brief GPIO device name: GPIOE */
#define BOARD_LED_GREEN_GPIO_PIN 6U                        /*!<@brief PORTE pin index: 6 */
#define BOARD_LED_GREEN_PORT PORTE                         /*!<@brief PORT device name: PORTE */
#define BOARD_LED_GREEN_PIN 6U                             /*!<@brief PORTE pin index: 6 */
#define BOARD_LED_GREEN_CHANNEL 6                          /*!<@brief GPIOE GPIO channel: 6 */
#define BOARD_LED_GREEN_PIN_NAME PTE6                      /*!<@brief Pin name */
#define BOARD_LED_GREEN_LABEL "LEDRGB_GREEN"               /*!<@brief Label */
#define BOARD_LED_GREEN_NAME "LED_GREEN"                   /*!<@brief Identifier name */
#define BOARD_LED_GREEN_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                           /* @} */

/*! @name PORTC9 (coord D7), LEDRGB_RED
  @{ */
#define BOARD_LED_RED_PERIPHERAL GPIOC                   /*!<@brief Device name: GPIOC */
#define BOARD_LED_RED_SIGNAL GPIO                        /*!<@brief GPIOC signal: GPIO */
#define BOARD_LED_RED_GPIO GPIOC                         /*!<@brief GPIO device name: GPIOC */
#define BOARD_LED_RED_GPIO_PIN 9U                        /*!<@brief PORTC pin index: 9 */
#define BOARD_LED_RED_PORT PORTC                         /*!<@brief PORT device name: PORTC */
#define BOARD_LED_RED_PIN 9U                             /*!<@brief PORTC pin index: 9 */
#define BOARD_LED_RED_CHANNEL 9                          /*!<@brief GPIOC GPIO channel: 9 */
#define BOARD_LED_RED_PIN_NAME PTC9                      /*!<@brief Pin name */
#define BOARD_LED_RED_LABEL "LEDRGB_RED"                 /*!<@brief Label */
#define BOARD_LED_RED_NAME "LED_RED"                     /*!<@brief Identifier name */
#define BOARD_LED_RED_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDs(void);

#define PORT_DFER_DFE_8_MASK 0x0100u /*!<@brief Digital Filter Enable Mask for item 8. */
#define PORT_DFER_DFE_9_MASK 0x0200u /*!<@brief Digital Filter Enable Mask for item 9. */

/*! @name PORTD8 (coord C9), U8[4]/U19[11]/I2C0_SCL
  @{ */
#define BOARD_ACCEL_SCL_PERIPHERAL I2C0                /*!<@brief Device name: I2C0 */
#define BOARD_ACCEL_SCL_SIGNAL SCL                     /*!<@brief I2C0 signal: SCL */
#define BOARD_ACCEL_SCL_PORT PORTD                     /*!<@brief PORT device name: PORTD */
#define BOARD_ACCEL_SCL_PIN 8U                         /*!<@brief PORTD pin index: 8 */
#define BOARD_ACCEL_SCL_PIN_NAME I2C0_SCL              /*!<@brief Pin name */
#define BOARD_ACCEL_SCL_LABEL "U8[4]/U19[11]/I2C0_SCL" /*!<@brief Label */
#define BOARD_ACCEL_SCL_NAME "ACCEL_SCL"               /*!<@brief Identifier name */
                                                       /* @} */

/*! @name PORTD9 (coord B9), U8[6]/U19[12]/I2C0_SDA
  @{ */
#define BOARD_ACCEL_SDA_PERIPHERAL I2C0                /*!<@brief Device name: I2C0 */
#define BOARD_ACCEL_SDA_SIGNAL SDA                     /*!<@brief I2C0 signal: SDA */
#define BOARD_ACCEL_SDA_PORT PORTD                     /*!<@brief PORT device name: PORTD */
#define BOARD_ACCEL_SDA_PIN 9U                         /*!<@brief PORTD pin index: 9 */
#define BOARD_ACCEL_SDA_PIN_NAME I2C0_SDA              /*!<@brief Pin name */
#define BOARD_ACCEL_SDA_LABEL "U8[6]/U19[12]/I2C0_SDA" /*!<@brief Label */
#define BOARD_ACCEL_SDA_NAME "ACCEL_SDA"               /*!<@brief Identifier name */
                                                       /* @} */

/*! @name PORTC17 (coord D5), U8[11]/FXOS8700CQ_INT1
  @{ */
#define BOARD_ACCEL_INT1_PERIPHERAL GPIOC                  /*!<@brief Device name: GPIOC */
#define BOARD_ACCEL_INT1_SIGNAL GPIO                       /*!<@brief GPIOC signal: GPIO */
#define BOARD_ACCEL_INT1_GPIO GPIOC                        /*!<@brief GPIO device name: GPIOC */
#define BOARD_ACCEL_INT1_GPIO_PIN 17U                      /*!<@brief PORTC pin index: 17 */
#define BOARD_ACCEL_INT1_PORT PORTC                        /*!<@brief PORT device name: PORTC */
#define BOARD_ACCEL_INT1_PIN 17U                           /*!<@brief PORTC pin index: 17 */
#define BOARD_ACCEL_INT1_CHANNEL 17                        /*!<@brief GPIOC GPIO channel: 17 */
#define BOARD_ACCEL_INT1_PIN_NAME PTC17                    /*!<@brief Pin name */
#define BOARD_ACCEL_INT1_LABEL "U8[11]/FXOS8700CQ_INT1"    /*!<@brief Label */
#define BOARD_ACCEL_INT1_NAME "ACCEL_INT1"                 /*!<@brief Identifier name */
#define BOARD_ACCEL_INT1_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                           /* @} */

/*! @name PORTC13 (coord D6), U8[9]/FXOS8700CQ_INT2
  @{ */
#define BOARD_ACCEL_INT2_PERIPHERAL GPIOC                  /*!<@brief Device name: GPIOC */
#define BOARD_ACCEL_INT2_SIGNAL GPIO                       /*!<@brief GPIOC signal: GPIO */
#define BOARD_ACCEL_INT2_GPIO GPIOC                        /*!<@brief GPIO device name: GPIOC */
#define BOARD_ACCEL_INT2_GPIO_PIN 13U                      /*!<@brief PORTC pin index: 13 */
#define BOARD_ACCEL_INT2_PORT PORTC                        /*!<@brief PORT device name: PORTC */
#define BOARD_ACCEL_INT2_PIN 13U                           /*!<@brief PORTC pin index: 13 */
#define BOARD_ACCEL_INT2_CHANNEL 13                        /*!<@brief GPIOC GPIO channel: 13 */
#define BOARD_ACCEL_INT2_PIN_NAME PTC13                    /*!<@brief Pin name */
#define BOARD_ACCEL_INT2_LABEL "U8[9]/FXOS8700CQ_INT2"     /*!<@brief Label */
#define BOARD_ACCEL_INT2_NAME "ACCEL_INT2"                 /*!<@brief Identifier name */
#define BOARD_ACCEL_INT2_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitACCEL_I2C(void);

#define PORT_DFER_DFE_8_MASK 0x0100u /*!<@brief Digital Filter Enable Mask for item 8. */
#define PORT_DFER_DFE_9_MASK 0x0200u /*!<@brief Digital Filter Enable Mask for item 9. */

/*! @name PORTD9 (coord B9), U8[6]/U19[12]/I2C0_SDA
  @{ */
#define BOARD_GYRO_SDA_PERIPHERAL I2C0                /*!<@brief Device name: I2C0 */
#define BOARD_GYRO_SDA_SIGNAL SDA                     /*!<@brief I2C0 signal: SDA */
#define BOARD_GYRO_SDA_PORT PORTD                     /*!<@brief PORT device name: PORTD */
#define BOARD_GYRO_SDA_PIN 9U                         /*!<@brief PORTD pin index: 9 */
#define BOARD_GYRO_SDA_PIN_NAME I2C0_SDA              /*!<@brief Pin name */
#define BOARD_GYRO_SDA_LABEL "U8[6]/U19[12]/I2C0_SDA" /*!<@brief Label */
#define BOARD_GYRO_SDA_NAME "GYRO_SDA"                /*!<@brief Identifier name */
                                                      /* @} */

/*! @name PORTD8 (coord C9), U8[4]/U19[11]/I2C0_SCL
  @{ */
#define BOARD_GYRO_SCL_PERIPHERAL I2C0                /*!<@brief Device name: I2C0 */
#define BOARD_GYRO_SCL_SIGNAL SCL                     /*!<@brief I2C0 signal: SCL */
#define BOARD_GYRO_SCL_PORT PORTD                     /*!<@brief PORT device name: PORTD */
#define BOARD_GYRO_SCL_PIN 8U                         /*!<@brief PORTD pin index: 8 */
#define BOARD_GYRO_SCL_PIN_NAME I2C0_SCL              /*!<@brief Pin name */
#define BOARD_GYRO_SCL_LABEL "U8[4]/U19[11]/I2C0_SCL" /*!<@brief Label */
#define BOARD_GYRO_SCL_NAME "GYRO_SCL"                /*!<@brief Identifier name */
                                                      /* @} */

/*! @name PORTA29 (coord H11), U19[3]/FXAS21002_INT1
  @{ */
#define BOARD_GYRO_INT1_PERIPHERAL GPIOA                  /*!<@brief Device name: GPIOA */
#define BOARD_GYRO_INT1_SIGNAL GPIO                       /*!<@brief GPIOA signal: GPIO */
#define BOARD_GYRO_INT1_GPIO GPIOA                        /*!<@brief GPIO device name: GPIOA */
#define BOARD_GYRO_INT1_GPIO_PIN 29U                      /*!<@brief PORTA pin index: 29 */
#define BOARD_GYRO_INT1_PORT PORTA                        /*!<@brief PORT device name: PORTA */
#define BOARD_GYRO_INT1_PIN 29U                           /*!<@brief PORTA pin index: 29 */
#define BOARD_GYRO_INT1_CHANNEL 29                        /*!<@brief GPIOA GPIO channel: 29 */
#define BOARD_GYRO_INT1_PIN_NAME PTA29                    /*!<@brief Pin name */
#define BOARD_GYRO_INT1_LABEL "U19[3]/FXAS21002_INT1"     /*!<@brief Label */
#define BOARD_GYRO_INT1_NAME "GYRO_INT1"                  /*!<@brief Identifier name */
#define BOARD_GYRO_INT1_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                          /* @} */

/*! @name PORTA28 (coord H12), U19[2]/FXAS21002_INT2
  @{ */
#define BOARD_GYRO_INT2_PERIPHERAL GPIOA                  /*!<@brief Device name: GPIOA */
#define BOARD_GYRO_INT2_SIGNAL GPIO                       /*!<@brief GPIOA signal: GPIO */
#define BOARD_GYRO_INT2_GPIO GPIOA                        /*!<@brief GPIO device name: GPIOA */
#define BOARD_GYRO_INT2_GPIO_PIN 28U                      /*!<@brief PORTA pin index: 28 */
#define BOARD_GYRO_INT2_PORT PORTA                        /*!<@brief PORT device name: PORTA */
#define BOARD_GYRO_INT2_PIN 28U                           /*!<@brief PORTA pin index: 28 */
#define BOARD_GYRO_INT2_CHANNEL 28                        /*!<@brief GPIOA GPIO channel: 28 */
#define BOARD_GYRO_INT2_PIN_NAME PTA28                    /*!<@brief Pin name */
#define BOARD_GYRO_INT2_LABEL "U19[2]/FXAS21002_INT2"     /*!<@brief Label */
#define BOARD_GYRO_INT2_NAME "GYRO_INT2"                  /*!<@brief Identifier name */
#define BOARD_GYRO_INT2_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitGYRO_I2C(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTB16 (coord E10), U7[4]/UART0_RX
  @{ */
#define BOARD_DEBUG_UART_RX_PERIPHERAL UART0       /*!<@brief Device name: UART0 */
#define BOARD_DEBUG_UART_RX_SIGNAL RX              /*!<@brief UART0 signal: RX */
#define BOARD_DEBUG_UART_RX_PORT PORTB             /*!<@brief PORT device name: PORTB */
#define BOARD_DEBUG_UART_RX_PIN 16U                /*!<@brief PORTB pin index: 16 */
#define BOARD_DEBUG_UART_RX_PIN_NAME UART0_RX      /*!<@brief Pin name */
#define BOARD_DEBUG_UART_RX_LABEL "U7[4]/UART0_RX" /*!<@brief Label */
#define BOARD_DEBUG_UART_RX_NAME "DEBUG_UART_RX"   /*!<@brief Identifier name */
                                                   /* @} */

/*! @name PORTB17 (coord E9), U10[1]/UART0_TX
  @{ */
#define BOARD_DEBUG_UART_TX_PERIPHERAL UART0                   /*!<@brief Device name: UART0 */
#define BOARD_DEBUG_UART_TX_SIGNAL TX                          /*!<@brief UART0 signal: TX */
#define BOARD_DEBUG_UART_TX_PORT PORTB                         /*!<@brief PORT device name: PORTB */
#define BOARD_DEBUG_UART_TX_PIN 17U                            /*!<@brief PORTB pin index: 17 */
#define BOARD_DEBUG_UART_TX_PIN_NAME UART0_TX                  /*!<@brief Pin name */
#define BOARD_DEBUG_UART_TX_LABEL "U10[1]/UART0_TX"            /*!<@brief Label */
#define BOARD_DEBUG_UART_TX_NAME "DEBUG_UART_TX"               /*!<@brief Identifier name */
#define BOARD_DEBUG_UART_TX_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UART(void);

#define PORT_DFER_DFE_10_MASK 0x0400u /*!<@brief Digital Filter Enable Mask for item 10. */

/*! @name PORTE3 (coord E4), SDHC0_CMD
  @{ */
#define BOARD_SDHC0_CMD_PERIPHERAL SDHC    /*!<@brief Device name: SDHC */
#define BOARD_SDHC0_CMD_SIGNAL CMD         /*!<@brief SDHC signal: CMD */
#define BOARD_SDHC0_CMD_PORT PORTE         /*!<@brief PORT device name: PORTE */
#define BOARD_SDHC0_CMD_PIN 3U             /*!<@brief PORTE pin index: 3 */
#define BOARD_SDHC0_CMD_PIN_NAME SDHC0_CMD /*!<@brief Pin name */
#define BOARD_SDHC0_CMD_LABEL "SDHC0_CMD"  /*!<@brief Label */
#define BOARD_SDHC0_CMD_NAME "SDHC0_CMD"   /*!<@brief Identifier name */
                                           /* @} */

/*! @name PORTE1 (coord D2), SDHC0_D0
  @{ */
#define BOARD_SDHC0_D0_PERIPHERAL SDHC   /*!<@brief Device name: SDHC */
#define BOARD_SDHC0_D0_SIGNAL DATA       /*!<@brief SDHC signal: DATA */
#define BOARD_SDHC0_D0_PORT PORTE        /*!<@brief PORT device name: PORTE */
#define BOARD_SDHC0_D0_PIN 1U            /*!<@brief PORTE pin index: 1 */
#define BOARD_SDHC0_D0_CHANNEL 0         /*!<@brief SDHC DATA channel: 0 */
#define BOARD_SDHC0_D0_PIN_NAME SDHC0_D0 /*!<@brief Pin name */
#define BOARD_SDHC0_D0_LABEL "SDHC0_D0"  /*!<@brief Label */
#define BOARD_SDHC0_D0_NAME "SDHC0_D0"   /*!<@brief Identifier name */
                                         /* @} */

/*! @name PORTE0 (coord D3), SDHC0_D1
  @{ */
#define BOARD_SDHC0_D1_PERIPHERAL SDHC   /*!<@brief Device name: SDHC */
#define BOARD_SDHC0_D1_SIGNAL DATA       /*!<@brief SDHC signal: DATA */
#define BOARD_SDHC0_D1_PORT PORTE        /*!<@brief PORT device name: PORTE */
#define BOARD_SDHC0_D1_PIN 0U            /*!<@brief PORTE pin index: 0 */
#define BOARD_SDHC0_D1_CHANNEL 1         /*!<@brief SDHC DATA channel: 1 */
#define BOARD_SDHC0_D1_PIN_NAME SDHC0_D1 /*!<@brief Pin name */
#define BOARD_SDHC0_D1_LABEL "SDHC0_D1"  /*!<@brief Label */
#define BOARD_SDHC0_D1_NAME "SDHC0_D1"   /*!<@brief Identifier name */
                                         /* @} */

/*! @name PORTE5 (coord E2), SDHC0_D2
  @{ */
#define BOARD_SDHC0_D2_PERIPHERAL SDHC   /*!<@brief Device name: SDHC */
#define BOARD_SDHC0_D2_SIGNAL DATA       /*!<@brief SDHC signal: DATA */
#define BOARD_SDHC0_D2_PORT PORTE        /*!<@brief PORT device name: PORTE */
#define BOARD_SDHC0_D2_PIN 5U            /*!<@brief PORTE pin index: 5 */
#define BOARD_SDHC0_D2_CHANNEL 2         /*!<@brief SDHC DATA channel: 2 */
#define BOARD_SDHC0_D2_PIN_NAME SDHC0_D2 /*!<@brief Pin name */
#define BOARD_SDHC0_D2_LABEL "SDHC0_D2"  /*!<@brief Label */
#define BOARD_SDHC0_D2_NAME "SDHC0_D2"   /*!<@brief Identifier name */
                                         /* @} */

/*! @name PORTE4 (coord E3), SDHC0_D3
  @{ */
#define BOARD_SDHC0_D3_PERIPHERAL SDHC   /*!<@brief Device name: SDHC */
#define BOARD_SDHC0_D3_SIGNAL DATA       /*!<@brief SDHC signal: DATA */
#define BOARD_SDHC0_D3_PORT PORTE        /*!<@brief PORT device name: PORTE */
#define BOARD_SDHC0_D3_PIN 4U            /*!<@brief PORTE pin index: 4 */
#define BOARD_SDHC0_D3_CHANNEL 3         /*!<@brief SDHC DATA channel: 3 */
#define BOARD_SDHC0_D3_PIN_NAME SDHC0_D3 /*!<@brief Pin name */
#define BOARD_SDHC0_D3_LABEL "SDHC0_D3"  /*!<@brief Label */
#define BOARD_SDHC0_D3_NAME "SDHC0_D3"   /*!<@brief Identifier name */
                                         /* @} */

/*! @name PORTE2 (coord D1), SDHC0_DCLK
  @{ */
#define BOARD_SDHC0_DCLK_PERIPHERAL SDHC     /*!<@brief Device name: SDHC */
#define BOARD_SDHC0_DCLK_SIGNAL DCLK         /*!<@brief SDHC signal: DCLK */
#define BOARD_SDHC0_DCLK_PORT PORTE          /*!<@brief PORT device name: PORTE */
#define BOARD_SDHC0_DCLK_PIN 2U              /*!<@brief PORTE pin index: 2 */
#define BOARD_SDHC0_DCLK_PIN_NAME SDHC0_DCLK /*!<@brief Pin name */
#define BOARD_SDHC0_DCLK_LABEL "SDHC0_DCLK"  /*!<@brief Label */
#define BOARD_SDHC0_DCLK_NAME "SDHC0_DCLK"   /*!<@brief Identifier name */
                                             /* @} */

/*! @name PORTD10 (coord B3), SD_CARD_DETECT
  @{ */
#define BOARD_SDCARD_CARD_DETECTION_PERIPHERAL GPIOD                  /*!<@brief Device name: GPIOD */
#define BOARD_SDCARD_CARD_DETECTION_SIGNAL GPIO                       /*!<@brief GPIOD signal: GPIO */
#define BOARD_SDCARD_CARD_DETECTION_GPIO GPIOD                        /*!<@brief GPIO device name: GPIOD */
#define BOARD_SDCARD_CARD_DETECTION_GPIO_PIN 10U                      /*!<@brief PORTD pin index: 10 */
#define BOARD_SDCARD_CARD_DETECTION_PORT PORTD                        /*!<@brief PORT device name: PORTD */
#define BOARD_SDCARD_CARD_DETECTION_PIN 10U                           /*!<@brief PORTD pin index: 10 */
#define BOARD_SDCARD_CARD_DETECTION_CHANNEL 10                        /*!<@brief GPIOD GPIO channel: 10 */
#define BOARD_SDCARD_CARD_DETECTION_PIN_NAME PTD10                    /*!<@brief Pin name */
#define BOARD_SDCARD_CARD_DETECTION_LABEL "SD_CARD_DETECT"            /*!<@brief Label */
#define BOARD_SDCARD_CARD_DETECTION_NAME "SDCARD_CARD_DETECTION"      /*!<@brief Identifier name */
#define BOARD_SDCARD_CARD_DETECTION_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSDHC0(void);

#define SOPT2_RMIISRC_ENET 0x01u /*!<@brief RMII clock source select: External bypass clock (ENET_1588_CLKIN). */

/*! @name PORTE26 (coord K4), U13[16]/ETHERNET_CLOCK
  @{ */
#define BOARD_ETHERNET_CLOCK_PERIPHERAL ENET                /*!<@brief Device name: ENET */
#define BOARD_ETHERNET_CLOCK_SIGNAL RMII_CLKIN              /*!<@brief ENET signal: RMII_CLKIN */
#define BOARD_ETHERNET_CLOCK_PORT PORTE                     /*!<@brief PORT device name: PORTE */
#define BOARD_ETHERNET_CLOCK_PIN 26U                        /*!<@brief PORTE pin index: 26 */
#define BOARD_ETHERNET_CLOCK_PIN_NAME ENET_1588_CLKIN       /*!<@brief Pin name */
#define BOARD_ETHERNET_CLOCK_LABEL "U13[16]/ETHERNET_CLOCK" /*!<@brief Label */
#define BOARD_ETHERNET_CLOCK_NAME "ETHERNET_CLOCK"          /*!<@brief Identifier name */
                                                            /* @} */

/*! @name PORTA14 (coord L10), U13[15]/RMII0_CRS_DV
  @{ */
#define BOARD_RMII0_CRS_DV_PERIPHERAL ENET              /*!<@brief Device name: ENET */
#define BOARD_RMII0_CRS_DV_SIGNAL RMII_CRS_DV           /*!<@brief ENET signal: RMII_CRS_DV */
#define BOARD_RMII0_CRS_DV_PORT PORTA                   /*!<@brief PORT device name: PORTA */
#define BOARD_RMII0_CRS_DV_PIN 14U                      /*!<@brief PORTA pin index: 14 */
#define BOARD_RMII0_CRS_DV_PIN_NAME RMII0_CRS_DV        /*!<@brief Pin name */
#define BOARD_RMII0_CRS_DV_LABEL "U13[15]/RMII0_CRS_DV" /*!<@brief Label */
#define BOARD_RMII0_CRS_DV_NAME "RMII0_CRS_DV"          /*!<@brief Identifier name */
                                                        /* @} */

/*! @name PORTB1 (coord H9), U13[11]/RMII0_MDC
  @{ */
#define BOARD_RMII0_MDC_PERIPHERAL ENET           /*!<@brief Device name: ENET */
#define BOARD_RMII0_MDC_SIGNAL RMII_MDC           /*!<@brief ENET signal: RMII_MDC */
#define BOARD_RMII0_MDC_PORT PORTB                /*!<@brief PORT device name: PORTB */
#define BOARD_RMII0_MDC_PIN 1U                    /*!<@brief PORTB pin index: 1 */
#define BOARD_RMII0_MDC_PIN_NAME RMII0_MDC        /*!<@brief Pin name */
#define BOARD_RMII0_MDC_LABEL "U13[11]/RMII0_MDC" /*!<@brief Label */
#define BOARD_RMII0_MDC_NAME "RMII0_MDC"          /*!<@brief Identifier name */
                                                  /* @} */

/*! @name PORTB0 (coord H10), U13[10]/RMII0_MDIO
  @{ */
#define BOARD_RMII0_MDIO_PERIPHERAL ENET            /*!<@brief Device name: ENET */
#define BOARD_RMII0_MDIO_SIGNAL RMII_MDIO           /*!<@brief ENET signal: RMII_MDIO */
#define BOARD_RMII0_MDIO_PORT PORTB                 /*!<@brief PORT device name: PORTB */
#define BOARD_RMII0_MDIO_PIN 0U                     /*!<@brief PORTB pin index: 0 */
#define BOARD_RMII0_MDIO_PIN_NAME RMII0_MDIO        /*!<@brief Pin name */
#define BOARD_RMII0_MDIO_LABEL "U13[10]/RMII0_MDIO" /*!<@brief Label */
#define BOARD_RMII0_MDIO_NAME "RMII0_MDIO"          /*!<@brief Identifier name */
                                                    /* @} */

/*! @name PORTA13 (coord J9), U13[13]/RMII0_RXD0
  @{ */
#define BOARD_RMII0_RXD0_PERIPHERAL ENET            /*!<@brief Device name: ENET */
#define BOARD_RMII0_RXD0_SIGNAL RMII_RXD0           /*!<@brief ENET signal: RMII_RXD0 */
#define BOARD_RMII0_RXD0_PORT PORTA                 /*!<@brief PORT device name: PORTA */
#define BOARD_RMII0_RXD0_PIN 13U                    /*!<@brief PORTA pin index: 13 */
#define BOARD_RMII0_RXD0_PIN_NAME RMII0_RXD0        /*!<@brief Pin name */
#define BOARD_RMII0_RXD0_LABEL "U13[13]/RMII0_RXD0" /*!<@brief Label */
#define BOARD_RMII0_RXD0_NAME "RMII0_RXD0"          /*!<@brief Identifier name */
                                                    /* @} */

/*! @name PORTA12 (coord K9), U13[12]/RMII0_RXD1
  @{ */
#define BOARD_RMII0_RXD1_PERIPHERAL ENET            /*!<@brief Device name: ENET */
#define BOARD_RMII0_RXD1_SIGNAL RMII_RXD1           /*!<@brief ENET signal: RMII_RXD1 */
#define BOARD_RMII0_RXD1_PORT PORTA                 /*!<@brief PORT device name: PORTA */
#define BOARD_RMII0_RXD1_PIN 12U                    /*!<@brief PORTA pin index: 12 */
#define BOARD_RMII0_RXD1_PIN_NAME RMII0_RXD1        /*!<@brief Pin name */
#define BOARD_RMII0_RXD1_LABEL "U13[12]/RMII0_RXD1" /*!<@brief Label */
#define BOARD_RMII0_RXD1_NAME "RMII0_RXD1"          /*!<@brief Identifier name */
                                                    /* @} */

/*! @name PORTA5 (coord M8), U13[17]/RMII0_RXER
  @{ */
#define BOARD_RMII0_RXER_PERIPHERAL ENET            /*!<@brief Device name: ENET */
#define BOARD_RMII0_RXER_SIGNAL RMII_RXER           /*!<@brief ENET signal: RMII_RXER */
#define BOARD_RMII0_RXER_PORT PORTA                 /*!<@brief PORT device name: PORTA */
#define BOARD_RMII0_RXER_PIN 5U                     /*!<@brief PORTA pin index: 5 */
#define BOARD_RMII0_RXER_PIN_NAME RMII0_RXER        /*!<@brief Pin name */
#define BOARD_RMII0_RXER_LABEL "U13[17]/RMII0_RXER" /*!<@brief Label */
#define BOARD_RMII0_RXER_NAME "RMII0_RXER"          /*!<@brief Identifier name */
                                                    /* @} */

/*! @name PORTA16 (coord K10), U13[20]/RMII0_TXD_0
  @{ */
#define BOARD_RMII0_TXD_0_PERIPHERAL ENET             /*!<@brief Device name: ENET */
#define BOARD_RMII0_TXD_0_SIGNAL RMII_TXD0            /*!<@brief ENET signal: RMII_TXD0 */
#define BOARD_RMII0_TXD_0_PORT PORTA                  /*!<@brief PORT device name: PORTA */
#define BOARD_RMII0_TXD_0_PIN 16U                     /*!<@brief PORTA pin index: 16 */
#define BOARD_RMII0_TXD_0_PIN_NAME RMII0_TXD0         /*!<@brief Pin name */
#define BOARD_RMII0_TXD_0_LABEL "U13[20]/RMII0_TXD_0" /*!<@brief Label */
#define BOARD_RMII0_TXD_0_NAME "RMII0_TXD_0"          /*!<@brief Identifier name */
                                                      /* @} */

/*! @name PORTA17 (coord K11), U13[21]/RMII0_TXD_1
  @{ */
#define BOARD_RMII0_TXD_1_PERIPHERAL ENET             /*!<@brief Device name: ENET */
#define BOARD_RMII0_TXD_1_SIGNAL RMII_TXD1            /*!<@brief ENET signal: RMII_TXD1 */
#define BOARD_RMII0_TXD_1_PORT PORTA                  /*!<@brief PORT device name: PORTA */
#define BOARD_RMII0_TXD_1_PIN 17U                     /*!<@brief PORTA pin index: 17 */
#define BOARD_RMII0_TXD_1_PIN_NAME RMII0_TXD1         /*!<@brief Pin name */
#define BOARD_RMII0_TXD_1_LABEL "U13[21]/RMII0_TXD_1" /*!<@brief Label */
#define BOARD_RMII0_TXD_1_NAME "RMII0_TXD_1"          /*!<@brief Identifier name */
                                                      /* @} */

/*! @name PORTA15 (coord L11), U13[19]/RMII0_TXEN
  @{ */
#define BOARD_RMII0_TXEN_PERIPHERAL ENET            /*!<@brief Device name: ENET */
#define BOARD_RMII0_TXEN_SIGNAL RMII_TXEN           /*!<@brief ENET signal: RMII_TXEN */
#define BOARD_RMII0_TXEN_PORT PORTA                 /*!<@brief PORT device name: PORTA */
#define BOARD_RMII0_TXEN_PIN 15U                    /*!<@brief PORTA pin index: 15 */
#define BOARD_RMII0_TXEN_PIN_NAME RMII0_TXEN        /*!<@brief Pin name */
#define BOARD_RMII0_TXEN_LABEL "U13[19]/RMII0_TXEN" /*!<@brief Label */
#define BOARD_RMII0_TXEN_NAME "RMII0_TXEN"          /*!<@brief Identifier name */
                                                    /* @} */

/*! @name PORTE26 (coord K4), U13[16]/ETHERNET_CLOCK
  @{ */
#define BOARD_ENET_1588_CLKIN_PERIPHERAL ENET                /*!<@brief Device name: ENET */
#define BOARD_ENET_1588_CLKIN_SIGNAL CLKIN_1588              /*!<@brief ENET signal: CLKIN_1588 */
#define BOARD_ENET_1588_CLKIN_PORT PORTE                     /*!<@brief PORT device name: PORTE */
#define BOARD_ENET_1588_CLKIN_PIN 26U                        /*!<@brief PORTE pin index: 26 */
#define BOARD_ENET_1588_CLKIN_PIN_NAME ENET_1588_CLKIN       /*!<@brief Pin name */
#define BOARD_ENET_1588_CLKIN_LABEL "U13[16]/ETHERNET_CLOCK" /*!<@brief Label */
#define BOARD_ENET_1588_CLKIN_NAME "ENET_1588_CLKIN"         /*!<@brief Identifier name */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitENET(void);

/*! @name USB1_DM (coord K1), K66_MICRO_USB_DN
  @{ */
#define BOARD_K66_MICRO_USB_DN_DCD_PERIPHERAL USBHSDCD         /*!<@brief Device name: USBHSDCD */
#define BOARD_K66_MICRO_USB_DN_DCD_SIGNAL DM                   /*!<@brief USBHSDCD signal: DM */
#define BOARD_K66_MICRO_USB_DN_DCD_PIN_NAME USB1_DM            /*!<@brief Pin name */
#define BOARD_K66_MICRO_USB_DN_DCD_LABEL "K66_MICRO_USB_DN"    /*!<@brief Label */
#define BOARD_K66_MICRO_USB_DN_DCD_NAME "K66_MICRO_USB_DN_DCD" /*!<@brief Identifier name */
                                                               /* @} */

/*! @name USB1_DP (coord J1), K66_MICRO_USB_DP
  @{ */
#define BOARD_K66_MICRO_USB_DP_DCD_PERIPHERAL USBHSDCD         /*!<@brief Device name: USBHSDCD */
#define BOARD_K66_MICRO_USB_DP_DCD_SIGNAL DP                   /*!<@brief USBHSDCD signal: DP */
#define BOARD_K66_MICRO_USB_DP_DCD_PIN_NAME USB1_DP            /*!<@brief Pin name */
#define BOARD_K66_MICRO_USB_DP_DCD_LABEL "K66_MICRO_USB_DP"    /*!<@brief Label */
#define BOARD_K66_MICRO_USB_DP_DCD_NAME "K66_MICRO_USB_DP_DCD" /*!<@brief Identifier name */
                                                               /* @} */

/*! @name USB1_DM (coord K1), K66_MICRO_USB_DN
  @{ */
#define BOARD_K66_MICRO_USB_DN_PHY_PERIPHERAL USBPHY           /*!<@brief Device name: USBPHY */
#define BOARD_K66_MICRO_USB_DN_PHY_SIGNAL DM                   /*!<@brief USBPHY signal: DM */
#define BOARD_K66_MICRO_USB_DN_PHY_PIN_NAME USB1_DM            /*!<@brief Pin name */
#define BOARD_K66_MICRO_USB_DN_PHY_LABEL "K66_MICRO_USB_DN"    /*!<@brief Label */
#define BOARD_K66_MICRO_USB_DN_PHY_NAME "K66_MICRO_USB_DN_PHY" /*!<@brief Identifier name */
                                                               /* @} */

/*! @name USB1_DP (coord J1), K66_MICRO_USB_DP
  @{ */
#define BOARD_K66_MICRO_USB_DP_PHY_PERIPHERAL USBPHY           /*!<@brief Device name: USBPHY */
#define BOARD_K66_MICRO_USB_DP_PHY_SIGNAL DP                   /*!<@brief USBPHY signal: DP */
#define BOARD_K66_MICRO_USB_DP_PHY_PIN_NAME USB1_DP            /*!<@brief Pin name */
#define BOARD_K66_MICRO_USB_DP_PHY_LABEL "K66_MICRO_USB_DP"    /*!<@brief Label */
#define BOARD_K66_MICRO_USB_DP_PHY_NAME "K66_MICRO_USB_DP_PHY" /*!<@brief Identifier name */
                                                               /* @} */

/*! @name PORTE10 (coord F1), USB_ID
  @{ */
#define BOARD_USB_ID_PERIPHERAL USBPHY /*!<@brief Device name: USBPHY */
#define BOARD_USB_ID_SIGNAL ID         /*!<@brief USBPHY signal: ID */
#define BOARD_USB_ID_PORT PORTE        /*!<@brief PORT device name: PORTE */
#define BOARD_USB_ID_PIN 10U           /*!<@brief PORTE pin index: 10 */
#define BOARD_USB_ID_PIN_NAME USB1_ID  /*!<@brief Pin name */
#define BOARD_USB_ID_LABEL "USB_ID"    /*!<@brief Label */
#define BOARD_USB_ID_NAME "USB_ID"     /*!<@brief Identifier name */
                                       /* @} */

/*! @name USB1_VBUS (coord L1), P5V_K66_USB
  @{ */
#define BOARD_P5V_K66_USB_PERIPHERAL USBPHY   /*!<@brief Device name: USBPHY */
#define BOARD_P5V_K66_USB_SIGNAL VBUS         /*!<@brief USBPHY signal: VBUS */
#define BOARD_P5V_K66_USB_PIN_NAME USB1_VBUS  /*!<@brief Pin name */
#define BOARD_P5V_K66_USB_LABEL "P5V_K66_USB" /*!<@brief Label */
#define BOARD_P5V_K66_USB_NAME "P5V_K66_USB"  /*!<@brief Identifier name */
                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUSB(void);

/*! @name PORTA18 (coord M12), EXTAL0
  @{ */
#define BOARD_EXTAL0_PERIPHERAL OSC  /*!<@brief Device name: OSC */
#define BOARD_EXTAL0_SIGNAL EXTAL0   /*!<@brief OSC signal: EXTAL0 */
#define BOARD_EXTAL0_PORT PORTA      /*!<@brief PORT device name: PORTA */
#define BOARD_EXTAL0_PIN 18U         /*!<@brief PORTA pin index: 18 */
#define BOARD_EXTAL0_PIN_NAME EXTAL0 /*!<@brief Pin name */
#define BOARD_EXTAL0_LABEL "EXTAL0"  /*!<@brief Label */
#define BOARD_EXTAL0_NAME "EXTAL0"   /*!<@brief Identifier name */
                                     /* @} */

/*! @name PORTA19 (coord M11), X501[3]
  @{ */
#define BOARD_XTAL0_PERIPHERAL OSC  /*!<@brief Device name: OSC */
#define BOARD_XTAL0_SIGNAL XTAL0    /*!<@brief OSC signal: XTAL0 */
#define BOARD_XTAL0_PORT PORTA      /*!<@brief PORT device name: PORTA */
#define BOARD_XTAL0_PIN 19U         /*!<@brief PORTA pin index: 19 */
#define BOARD_XTAL0_PIN_NAME XTAL0  /*!<@brief Pin name */
#define BOARD_XTAL0_LABEL "X501[3]" /*!<@brief Label */
#define BOARD_XTAL0_NAME "XTAL0"    /*!<@brief Identifier name */
                                    /* @} */

/*! @name EXTAL32 (coord M6), Y3[2]
  @{ */
#define BOARD_EXTAL32K_PERIPHERAL RTC   /*!<@brief Device name: RTC */
#define BOARD_EXTAL32K_SIGNAL EXTAL32   /*!<@brief RTC signal: EXTAL32 */
#define BOARD_EXTAL32K_PIN_NAME EXTAL32 /*!<@brief Pin name */
#define BOARD_EXTAL32K_LABEL "Y3[2]"    /*!<@brief Label */
#define BOARD_EXTAL32K_NAME "EXTAL32K"  /*!<@brief Identifier name */
                                        /* @} */

/*! @name XTAL32 (coord M7), Y3[1]
  @{ */
#define BOARD_XTAL32K_PERIPHERAL RTC  /*!<@brief Device name: RTC */
#define BOARD_XTAL32K_SIGNAL XTAL32   /*!<@brief RTC signal: XTAL32 */
#define BOARD_XTAL32K_PIN_NAME XTAL32 /*!<@brief Pin name */
#define BOARD_XTAL32K_LABEL "Y3[1]"   /*!<@brief Label */
#define BOARD_XTAL32K_NAME "XTAL32K"  /*!<@brief Identifier name */
                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitOSCs(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
